//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFlavour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int Author_ID { get; set; }
        public int Group_ID { get; set; }
        public Nullable<int> FullText_ID { get; set; }
        public string ImageLink { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Group Group { get; set; }
    }
}
