//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFlavour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int ID { get; set; }
        public string ImageLink { get; set; }
        public int ArticleID { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
